# Generated by Django 2.1.2 on 2018-10-31 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=200)])),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='myapp.Location', to_field='code'),
            preserve_default=False,
        ),
    ]
